development:
  adapter: jdbcmysql
  database: agentfarm_development
  reconnect: true
  pool: 20
  host: localhost
  username: root
  password: hokuto

test:
  adapter: jdbcmysql
  database: agentfarm_test
  reconnect: false
  pool: 20
  host: localhost
  username: root
  password: geograph

production:
  adapter: mysql
  xa: false
  database: geograph_production
  host: 10.100.0.1
  username: geograph
  password: geograph_passwd
  encoding: utf8
