development:
  adapter: jdbcmysql
  database: agentfarm_development
  reconnect: true
  pool: 20
  host: localhost
  username: root
  password: geograph

test:
  adapter: jdbcmysql
  database: agentfarm_test
  reconnect: false
  pool: 20
  host: localhost
  username: root
  password: geograph

production:
  adapter: jdbcmysql
  database: agentfarm_production
  host: localhost
  reconnect: true
  pool: 20
  username: root
  password: geograph
