development:
  adapter: jdbcmysql
  database: agentfarm_development
  reconnect: false
  pool: 20
  username: root
  password: geograph

test:
  adapter: jdbcmysql
  database: agentfarm_test
  reconnect: false
  pool: 20
  username: root
  password: geograph

production:
  adapter: jdbcmysql
  database: agentfarm_production
  host: 10.100.0.1
  reconnect: false
  pool: 20
  username: root
  password: geograph