queues:
  /queue/agents:
    durable: false

messaging:
  /topic/perceptions: 
    Madmass::PerceptionsProcessor:
  /queue/agents: 
    Madmass::AgentRunner:

#tasks:
#  Backgroundable:
#    concurrency: 5

#pooling:
#  messaging: shared


jobs:
  agent.group.runner:
    job:  AgentGroupRunner
    cron: '*/1 * * * * ?'
    description: Run Agent Groups
    singleton: true